L2b
stcorp/codadef-aeolus pull request #3
Opened 2022-06-21 09:42 UTC by srepmub

2022-06-21 13:44 UTC, baspijhor requested changes
Just one comment (see review).

2022-06-21 13:44 UTC, baspijhor commented on products/ALD_U_N_2B_03_80.xml
> +        <cd:NamedType id="Level_2B_Meas_PCD_ADSR_03_70"/>
This should be:
```suggestion
        <cd:NamedType id="Level_2B_Meas_PCD_ADSR_03_80"/>
```

2022-06-22 07:35 UTC, srepmub commented on products/ALD_U_N_2B_03_80.xml
> +        <cd:NamedType id="Level_2B_Meas_PCD_ADSR_03_70"/>
my grep-fu has failed me.

2022-06-22 10:08 UTC, baspijhor approved these changes

2022-06-22 10:09 UTC, merged